### PR TITLE
set dims and shape of OpticalSeries.data for RGB images

### LINKED ISSUE #316: OpticalSeries does not allow for RGB
The `dims` of `OpticalSeries` inherits from `ImageSeries`, which is:

```yaml
- - frame
   - x
   - y
- - frame
   - x
   - y
   - z
```
This makes it impossible to properly record the presentation of colored images. I would expect this to be the most common application of the neurodata_type. There are ways to present volumetric data to he subject, but presenting color images is much more common, and I am not aware of any groups using `OpticalSeries` to record the presentation of volumetric stimuli.

My preferred solution would be to change the shape of `OpticalSeries.data` to:

```yaml
- - frame
   - x
   - y
- - frame
   - x
   - y
   - r,g,b
```
This issue is currently blocking the Rutishauser lab, which is trying to write and publish a guide for converting data to NWB.

### PR DESCRIPTION
**Pull request by bendichter**
fix #316

### CODE REVIEW

**Review by oruebel — DISMISSED** [review]

**Review by rly — DISMISSED** [review]

**Review by rly — DISMISSED** [review]

**Comment by rly** [comment]
As this is a bugfix, I think this is fine to include in version 2.2.2 rather than 2.3.0.

**Comment by bendichter** [comment]
This requires an associated change on a pynwb branch, right?

**Comment by bendichter** [comment]
the doc is missing. This should not validate. Can we include the json-schema tests in the CI?

**Comment by rly** [comment]
@bendichter yes, this requires an associated change in PyNWB. I am working on the enh/update_schema branch for that.

The doc is missing, but isn't it inherited from `ImageSeries.data`?

**Comment by rly** [comment]
(To be sure, I would add a doc key anyway)

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
@bendichter please merge if this is ready to go. I have included your associated API change within PR https://github.com/NeurodataWithoutBorders/pynwb/pull/1146

**Pull request merged**
