### PR TITLE
Deprecate manifold in favor of pixel_origin and pixel_deltas

### PR DESCRIPTION
**Pull request by rly**
Implementing spec changes from https://github.com/NeurodataWithoutBorders/pynwb/pull/576

### CODE REVIEW

**Review by ajtritt — DISMISSED** [review]

**Comment by bendichter** [comment]
@rly can we merge this?

**Comment by rly** [comment]
@bendichter I have been hung up on the names of the replacement datasets. To me, they are not intuitive enough and "pixel" is not appropriate for 3D data. What do you think about "origin_coords" and "grid_spacing" instead?

**Comment by bendichter** [comment]
@rly Yeah, "origin_coords" and "grid_spacing" are good names

**Review by bendichter — APPROVED** [review]

**Comment by oruebel** [comment]
@rly @bendichter I assume the idea is to then also rename ``pixel_origin`` and ``pixel_deltas`` in NeurodataWithoutBorders/pynwb#576? Correct?

**Comment by bendichter** [comment]
@oruebel that's right. I think it will probably be easier to re-do that PR given how many merge conflicts there are

**Comment by oruebel** [comment]
Sounds good.

**Review by oruebel — APPROVED** [review]

**Comment by rly** [comment]
@bendichter can you make a new PR to replace https://github.com/NeurodataWithoutBorders/pynwb/pull/576 ?

**Comment by bendichter** [comment]
sure

**Pull request merged**
