### PR TITLE
ophys/imaging_rate: use float instead of text

### PR DESCRIPTION
**Pull request by jcfr**
See #136

### CODE REVIEW

**Comment by oruebel** [comment]
@jcfr did you update the schema and API class in PyNWB API for this too?

**Comment by jcfr** [comment]
> did you update the schema and API in PyNWB API for this too?

No. 

As soon as the change are integrated in this repo, anyone will be able to run the pynwb script [./src/pynwb/data/UpdateFromUpstream.sh](https://github.com/NeurodataWithoutBorders/pynwb/pull/506/files#diff-415d73cb9f0aaa0ccd472cb6cc88bd14) to sync with the updated schema

(@oruebel  to enable this, would appreciate if you could review https://github.com/NeurodataWithoutBorders/pynwb/pull/506)

Now the update of the API would have to be done as part of the PR updating the schema in pynwb. May be @bendichter  could take care of this ?

**Comment by oruebel** [comment]
@jcfr do I understand this correctly that the workflow here is to update the schema in nwb-schema first and to then catch up PyNWB to it? For consistency, it might be easier to do this the other way around, i.e. update the schema and API in PyNWB first and then push out the changes to nwb-schema.

**Comment by jcfr** [comment]
> workflow here is to update the schema in nwb-schema first and to then catch up PyNWB to it?

Indeed.

> it might be easier to do this the other way around, i.e. update the schema and API in PyNWB first and then push out the changes to nwb-schema.

Definitively agree :+1:

**Comment by oruebel** [comment]
The schema in PyNWB has changed quite a bit. I've ported and finished the changes in PyNWB (i.e., updated the container class and added tests). The changes will move over the this repo when we copy the schema from PyNWB to here. Closing this PR. The current PR for this is on the PyNWB repo here https://github.com/NeurodataWithoutBorders/pynwb/pull/612

**Pull request closed without merging**
