### PR TITLE
Update TimeIntervals.timeseries to use new TimeSeriesReferenceVectorData

### PR DESCRIPTION
**Pull request by oruebel**
## Motivation

#470 added the new ``TimeSeriesReferenceVectorData`` type. This PR updates ``TimeIntervals`` to use the new  ``TimeSeriesReferenceVectorData`` type. This does not alter the overall structure  of ``TimeIntervals`` in a major way aside from changing the value of the ``neurodata_type`` attribute in the file  from ``VectorData`` to ``TimeSeriesReferenceVectorData``. This change replaces the existing ``TimeIntervals.timeseries``   column with a ``TimeSeriesReferenceVectorData`` type column of the same name and overall schema. This change facilitate creating common functionality around ``TimeSeriesReferenceVectorData``. This change affects all existing ``TimeIntervals`` tables   as part of the ``intervals/`` group, i.e., ``intervals/epochs``, ``intervals/trials``, and ``intervals/invalid_times`` (#470)

## Summary of changes

- Update ``TimeIntervals`` to use the new ``TimeSeriesReferenceVectorData`` type

## Relates PRs

https://github.com/NeurodataWithoutBorders/pynwb/pull/1390 is the matching PR on PyNWB for this

## PR checklist for schema changes

- [x] Update the version string in `docs/format/source/conf.py`, `core/nwb.namespace.yaml`, and `/core/nwb.file.yaml`
  to the next version with the suffix "-alpha"
- [X] Add a new section in the release notes for the new version with the date "Upcoming"
- [X] Add release notes for the PR to `docs/format/source/format_release_notes.rst`

### CODE REVIEW

**Comment by rly** [comment]
Looks good. Please update the version strings in docs/format/source/conf.py, core/nwb.namespace.yaml, and /core/nwb.file.yaml to "2.5.0-alpha"

**Review by rly — DISMISSED** [review]

**Comment by rly** [comment]
Looks good. Feel free to squash and merge.

**Review by rly — DISMISSED** [review]

**Comment by CodyCBakerPhD** [comment]
Would this sort of reference object make sense to use for waveform columns on a UnitsTable? We often have difficulty getting the properties of that column to properly match TimeSeries-like attributes. What do you think @oruebel @bendichter 

> This change facilitate creating common functionality around TimeSeriesReferenceVectorData. This change affects all existing TimeIntervals tables as part of the intervals/ group, i.e., intervals/epochs, intervals/trials, and intervals/invalid_times

Would it also apply to custom TimeInterval table objects placed in, say, a 'processing' module?

**Comment by oruebel** [comment]
> Would it also apply to custom TimeInterval table objects placed in, say, a 'processing' module?

Yes, this updates the ``TimeIntervals`` type and as such will affect all ``TimeIntervals`` tables

> Would this sort of reference object make sense to use for waveform columns on a UnitsTable?

I'm not sure. This would require storing the waveforms in (likely many individual) ``TimeSeries`` and then referencing subsets of those TimeSeries. I'm not sure how well this would work here, in particular, I'm not sure about how many different TimeSeries objects would be required and what the performance for accessing the data would end up being as it will required resolving a lot of links.

**Review by rly — APPROVED** [review]

**Pull request merged**
