### PR TITLE
Prepare 2.5.0 release

### PR DESCRIPTION
**Pull request by rly**
To include:
- [x] #510 
- [x] #498 
- [x] #496 
- [x] #486 
- [x] https://github.com/NeurodataWithoutBorders/nwb-schema/pull/459

### CODE REVIEW

**Comment by bendichter** [comment]
@oruebel and I would like to add #512

**Comment by rly** [comment]
@lawrence-mbf NWB schema 2.5.0 is ready for release. Do you foresee any issues with adding support for these changes in MatNWB?

**Review by lawrence-mbf — DISMISSED** [review]
lgtm

**Review by bendichter — APPROVED** [review]
lgtm

**Pull request merged**
