### PR TITLE
NWB file session_start_time and file_create_date: Enforce ISO8601:2004(E) format

### PR DESCRIPTION
**Pull request by t-b**
To push #50 a bit further I decided to give it a shot via a PR.

### CODE REVIEW

**Comment by neuromusic** [comment]
Love it (though as I've said before, I'd prefer these fields to be "optional"). 

A few practical questions (mostly for @ajtritt)...

Since this isn't a native HDF5 type, how do we validate that files confirm? Does form need to check? If so, how does form know which fields need to be ISO8601?

**Comment by ajtritt** [comment]
We would have to create a time format within FORM.  The two options that come to mind are

1) leave time as string, and FORM has to enforce the string fits the format on read/write. 
2) create a named type. This makes it more machine-readable

Either way, read APIs would be have the freedom to return the data in whatever format. For example, for PyNWB, it could be returned as a datetime object.

**Comment by ajtritt** [comment]
Is there any disadvantage to taking @t-b's changes one step further, and requiring that time is always UTC?

**Comment by neuromusic** [comment]
> Is there any disadvantage to taking @t-b's changes one step further, and requiring that time is always UTC?

Yes.  ISO8601:2004(E) is an international standard. It is widely used and was not defined by us, so we aren't unnecessarily reinventing the wheel. Using ISO8601:2004(E) ensures that these pieces of metadata are machine-readable (which is not currently guaranteed) & human-readable without over-constraining the NWB standard. Any library that can validate ISO8601 strings or coerce its own datetime objects into ISO8601 conforms without any further requirements.

**Comment by t-b** [comment]
@ajtritt One disadvantage of always using UTC is also that one might argue that the timezone offset itself has information. 

With `named type` you mean a custom HDF5 data type? If yes, I would not recommend that as not all HDF5 APIs can read arbitraty custom datatypes (Java, Igor Pro, ...).

@neuromusic As I tried mentioning in the commit message we would allow only a subset of possible ISO8601 compliant date and time strings. This is done to make the correctness check easier.

**Comment by ajtritt** [comment]
Okay, sounds like ISO8601:2004(E) is the way to go. 
Named types are just compound data types that get saved to the file for use throughout. I would create compound type that consists of all the fields in the ISO8601:2004(E) format, store it in file, and then the file_create_date and session_start_time datasets would link to this type. 

We already allow compound types, as it is the basis for tables.

**Comment by t-b** [comment]
However we move forward on this issue. I suggest we at least teach pynwb to create timestamps in UTC timezone and not local timezone.

I just created a nwb file with latest `pynwb` and I get as timestamp "2018-04-03 14:16:28.158191" which is in PDT.

I can provide a PR of course.

**Comment by oruebel** [comment]
Closing for now. The schema has changed significantly (due to refactoring) in PyNWB. These changes should be implemented in PyNWB and then we can sync the schema over to this repo afterwards. See also #50

**Pull request closed without merging**
